frontend/package.json, frontend/pnpm-lock.yaml, frontend/src/pages/console.tsx
* Uses `ansi-html-community` package to convert messages with ansi color codes to HTML
=> Adds support for ansi color codes in log messages

frontend/package.json, frontend/pnpm-lock.yaml, frontend/src/pages/console.tsx
* Switched ansi parsing library to `ansi_up` to supports more ansi encodings
* Using dark background for ansi-encoded messages
=> Improves support for ansi color codes

frontend/index.html, frontend/src/components/layouts/AppLayout.tsx, frontend/src/lib/theme.tsx, frontend/src/main.tsx, frontend/src/pages/_root.tsx, frontend/src/pages/console.tsx
* Moved dark mode code into a provider
* Added snippet to index.html to add `dark` class to document as early as possible
=> Consolidates dark mode selector code

backend/cmd/server/config.go, backend/cmd/server/main.go, backend/hack/server.yaml, backend/internal/ginapp/config.go, backend/internal/ginapp/ginapp.go, backend/internal/ginapp/testutils_test.go
* Fixes https://github.com/kubetail-org/kubetail/issues/22
=> Adds session cookie `name` option

Dockerfile, backend/internal/ginapp/ginapp.go, hack/config.yaml
Fixes https://github.com/kubetail-org/kubetail/issues/29
=> Fixes issue with missing template directory in docker image

frontend/src/lib/console/logfeed.tsx
* Removes extra row in content viewer which was making the autoscroll detector more sensitive to changes
=> Fixes autoscroll issue

backend/graph/helpers.go
Fixes https://github.com/kubetail-org/kubetail/issues/2#issuecomment-2008949737
=> Handles ISO timestamps with tz when getting first timestamp in logs

frontend/src/components/layouts/AppLayout.tsx, frontend/src/components/widgets/Footer.tsx, frontend/src/pages/home.tsx
Fixes https://github.com/kubetail-org/kubetail/issues/46
=> Implements sticky footer for home page

.github/workflows/ci.yml
Changed action to all branches
=> Update and rename main.yml to ci.yml

.github/workflows/ci.yml, Dockerfile, backend/internal/ginapp/ginapp.go
* Fixed template directory issue preventing backend tests from passing
* Added testing to github ci workflow
=> Fixes golang unit tests and improves github workflow

frontend/src/lib/console/logfeed.tsx
* Improves method for tracking references to log feed data fetchers which fixes issue where pressing back then forward did nothing
=> Fixes issue where pressing back then forward does nothing

frontend/src/lib/console/logfeed.tsx
Increases autoscroll tolerance from 10 to 20 to fix intermittent issue with loss of autoscroll
=> Increases autoscroll tolerance

frontend/package.json, frontend/pnpm-lock.yaml, frontend/src/components/elements/Modal.tsx
* upgrades kubetail-ui -> 0.1.4
* adds missing initialFocus to use of <Dialog>
=> frontend upgrades and bug fixes

Dockerfile, frontend/src/main.tsx, frontend/vite.config.ts
* Removes unnecessary logging statement in main.tsx
* Adds sourcemaps to frontend build
* Upgrades node in docker build -> 20.13.1
* Upgrades pnpm in docker build -> 9.1.2
=> Improvements

README.md
Hey there! This is Jake from Glasskube. 
I have recently integrated Kubetail to Glasskube for easy upgrade maintenance and straightforward installation. 
Through this PR I wanted to add the simple steps for users to install Kubetail using Glasskube. 
In the coming days I will write a shorts guide for Kubetail which will be added to the [Glasskube guide section](https://glasskube.dev/guides/cert-manager/). 
Would love to hear your thoughts. 
Also including a screenshot of Kubetail as seen in the Glasskube UI
=> Update READEME.md to include Glasskube installation steps

modules/common/k8shelpers/keys.go, modules/common/k8shelpers/transport.go, modules/server/graph/helpers.go, modules/server/graph/resolver.go, modules/server/pkg/ginapp/ginapp_test.go, modules/server/pkg/ginapp/middleware.go
* Implements clientset caching
=> Adds speed optimizations to dashboard

dashboard-ui/src/apollo-client.ts, dashboard-ui/src/error-page.tsx, dashboard-ui/src/main.tsx, dashboard-ui/src/pages/_root.tsx
* Removes unnecessary `<ErrorBoundary>`
* Moves `<Suspense>` to _root.tsx so it doesn't hide toaster
* Added NetworkErrors to toaster
=> Improve error handling

modules/dashboard/graph/resolver.go, modules/dashboard/graph/schema.resolvers.go, modules/dashboard/graph/server.go, modules/dashboard/graph/server_test.go, modules/dashboard/internal/cluster-api/health-monitor-manager.go, modules/dashboard/internal/cluster-api/health-monitor.go, modules/dashboard/internal/cluster-api/helpers.go, modules/dashboard/pkg/app/app.go, modules/dashboard/pkg/app/testutils_test.go, modules/shared/config/config.go
* Removes unused resources from Tiltfile causing errors
* Updates config names causing errors in dev kubetail.yaml (api => cluster-api, agent => cluster-agent)
* Updates default ports in dashboard and cluster-api executable cli flags
=> Fix dev environment, updated default ports

modules/dashboard/pkg/app/website.go, modules/shared/middleware/middleware.go
* Add "Cache-Control: public, max-age=31536000, immutable" to dashboard static assets
=> Add cache-control headers to dashboard static assets

dashboard-ui/package.json, dashboard-ui/pnpm-lock.yaml
=> Upgrade vitest to fix security issue

dashboard-ui/src/lib/console/logfeed.tsx, dashboard-ui/src/pages/console.tsx
* Save head/tail/seek control interactions to url
=> Add state to dashboard console controls

dashboard-ui/src/components/widgets/SettingsDropdown.tsx, dashboard-ui/src/lib/workload.ts, dashboard-ui/src/pages/home.tsx
1) added a proper sidebar to switch between workloads and made it toggleable.
2) aligned the tables to adapt to the whole screen, but columns across tables are misaligned ( needs to be fixed in a upcoming pr ).
3) added a proper no results ui with some icon.
4) added search input and filter button on top of each table,only the ui, functionality in the next pr.
=> feat: Dashboard enhancement.

dashboard-ui/src/components/widgets/SourcePickerModal.tsx, dashboard-ui/src/lib/hooks.ts, dashboard-ui/src/lib/workload.ts, dashboard-ui/src/pages/home.tsx
- changed the sidebar toggle part.
- add a countBadge on sidebar items.
- show no resource found ui inside the table.
- hide show more option and show the whole table when viewing individual workloads.
- moved the useWorkloadCounter hook to a center location to reuse in source picker and dashboard sidebar.
https://github.com/user-attachments/assets/0998fa10-eac9-4f62-8e0d-ce3178a4873c
=> feat: More improvements in the dashboard.

crates/rgkl/Cargo.lock, crates/rgkl/Cargo.toml, crates/rgkl/src/main.rs, crates/rgkl/src/stream_backward.rs, crates/rgkl/src/stream_forward.rs, crates/rgkl/src/util/format.rs, crates/rgkl/src/util/matcher.rs, crates/rgkl/src/util/offset.rs, crates/rgkl/src/util/writer.rs, hack/ctlptl/minikube.yaml, hack/tilt/kubetail.yaml, modules/cluster-api/graph/resolver.go, modules/cluster-api/graph/resolver_test.go, modules/cluster-api/graph/schema.resolvers.go, modules/cluster-api/graph/schema.resolvers_test.go, modules/shared/k8shelpers/authorizer.go, modules/shared/k8shelpers/connection-manager.go, modules/shared/k8shelpers/connection-manager_test.go
* Centralize use of SharedFactoryInformer to decrease memory usage in Cluster API
* Add support for docker container runtime to rgkl
* Add auth tests to Cluster API to ensure non-empty bearer token
=> Decrease memory usage, add support for docker container runtime

.github/workflows/ci.yml, dashboard-ui/package.json, dashboard-ui/pnpm-lock.yaml
Fixes https://github.com/kubetail-org/kubetail/security/dependabot/77
=> sec: upgrade react-router (CVE-2025-43865)

modules/shared/k8shelpers/kube-config-watcher.go
=> cli: remove kubeconfig noisy logs

dashboard-ui/src/lib/hooks.ts, dashboard-ui/src/lib/logfeed.tsx, dashboard-ui/src/pages/console.test.tsx, dashboard-ui/src/pages/console.tsx, dashboard-ui/vitest.setup.ts
* Add `useIsClusterAPIEnabled()` hook
* Wait for hook to return true/false before rending console page
=> Add ClusterAPI check to console page

dashboard-ui/src/lib/logfeed.tsx, hack/ctlptl/minikube.yaml
* Fixes issue where new items added to virtualized list dynamically were being rendered with overlapping text
Fixes https://github.com/kubetail-org/kubetail/issues/195
=> Fix wrap bug

crates/rgkl/README.md
Some documentation on what the crate is, how it fits into kubetail, how to use it/what to use it for, dependencies, etc.
=> [docs] rgkl - Add README.md

modules/dashboard/internal/cluster-api/health-monitor.go
* If Kubernetes API doesn't support EndpointSlices, return NoopHealthWorker
=> Add EndpointSlices feature detection to health monitor (#251)

CODEOWNERS
@rxinui on CLI side
@amorey kubetail owner
=> doc: CODEOWNERS

dashboard-ui/src/components/widgets/SourcePickerModal.tsx
Added a fixed height to the sources list container.
Implemented a sticky header for the table.
Made the entire row clickable for selection.
=> Improve source picker UI

.github/pull_request_template.md, CODE_OF_CONDUCT.md, README.md
Fixes # 
Introduce a standard PR Template for Kubetail
A PR template file is added to `.github/` as default PR format for contributors
=> 📜 add PR template

.github/workflows/issues.yml
Fixes # 
Automate sync between Issues and Project
add new github actions workflow to automatically add issues into Project
=> 🐋 automate issues and project

.github/pull_request_template.md
Fix footnote markup in PR template
=> 📜 Fix footnote markup in PR template

README.md
=> 📜 Add Roadmap to README

.github/DISCUSSION_TEMPLATE/PRODUCT-SPEC.yml, .github/DISCUSSION_TEMPLATE/TECHNICAL-SPEC.yml
Add "Product Spec" and "Technical Spec" templates to GitHub discussions
- Add product spec template in .github/DISCUSSION_TEMPLATE/PRODUCT-SPEC.yml
- Add techincal spec template in .github/DISCUSSION_TEMPLATE/TECHNICAL-SPEC.yml
=> 🐋 Add "Product Spec" and "Technical Spec" templates to GitHub discussions

README.md
Add chocolatey install command to README
* Pluralized "Package Managers"
* Add Chocolatey install command to Package Managers Quickstart
=> 📜 Add chocolatey install command to README

.github/workflows/ci.yml
Add crates-lint, crates-vet to build step dependencies in CI workflow
- Modify .github/workflows/ci.yaml, add `crates-lint` and `crates-vet` to build steps' `needs` list
=> 🎣  Add crates-lint, crates-vet to build step dependencies in CI workflow

modules/dashboard/internal/cluster-api/health-monitor.go
Fixes #347
Fix race condition writing to map concurrently
- Moved from map to sync.Map
=> 🎣 Fix concurrent map write in DesktopHealthMonitor

AGENTS.md
=> 📜 Add agents.md

modules/dashboard/internal/cluster-api/health-monitor.go
🐋 feat(contextMu): replace map+mutex with SyncMap for contextMu (#395)
Fixes #395
Refactor contextMu to use util.SyncMap instead of map+mutex.  
This simplifies concurrent access and removes unnecessary locking logic.
- Changed `contextMu` from `map[string]*sync.Mutex` to `util.SyncMap[string, *sync.Mutex]`
- Removed `hm.mu` lock
- Updated usage to `LoadOrStore`
=> 🐋 feat(contextMu): replace map+mutex with SyncMap for contextMu (#395)

modules/cli/cmd/serve.go, modules/cli/internal/tunnel/tunnel.go
Fixes #387  
made newTunnel context aware 
added a ctx parameter to be passed into newTunnel
=> 🎣 makes newTunnel context aware

.github/workflows/release-cli.yml
Disable rpm release task to prevent this issue https://github.com/kubetail-org/kubetail/issues/454
=> 🎣 Temporarily disabled rpm release task

modules/dashboard/graph/schema.resolvers.go
Fixes #415
Prevent "Write on hijacked connection" error
- Check if context is closed before writing errors to websocket in dashboard
=> 🎣 Prevent write on closed connection

.github/workflows/publish-winget.yml, .github/workflows/release-cli.yml, .github/workflows/release-cluster-agent.yml, .github/workflows/release-cluster-api.yml, .github/workflows/release-dashboard.yml
Fixes #345 
Pin actions from individual developers in each Github workflow to specific git commits.
Commits are determined by the time we use the actions, not by the time the workflow file was written or committed to the repository. The following commit hashes represent the latest versions at the time of this PR:Actions that get pinned with specific commit:
- `robinraju/release-downloader@daf26c5` (v1.12)
- `peter-evans/create-pull-request@271a8d0` (v7.0.8) 
- `jiro4989/build-deb-action@975f7f3` (v4.2.1)
- `dcarbone/install-jq-action@f0e10f4` (v3.1.1)
=> ✨ Use specific commit hash for actions from individual developers

.github/actions/setup-environment/action.yml, .github/workflows/ci.yml
Fixes # [417](https://github.com/kubetail-org/kubetail/issues/417)
This PR consolidates the GitHub Actions CI workflow to improve reliability and maintainability by replacing separate Docker build jobs with a unified matrix strategy and adding timeout protection to prevent hanging builds.
- Consolidated Docker builds: Replaced separate docker-builds-amd64 and docker-builds-arm64 jobs with a single docker-builds job using matrix strategy
- Improved matrix organization: Each Docker image/architecture combination gets its own cache scope for better build performance
- Preserved existing functionality: All builds, tests, and CLI compilation remain unchanged
=> :recycle: Split CI into 2 files to improve readability and reusability

crates/rgkl/Cargo.lock, crates/rgkl/Cargo.toml
Fixes: #473 #472 #471 #470 #469 #468
Upgrade rgkl rust dependencies
=> ✨ Upgrade rgkl rust dependencies

dashboard-ui/package.json, dashboard-ui/pnpm-lock.yaml
Upgrade dashboard-ui dependencies
- postcss => 8.5.6
- Rebuilt pnpm-lock.yaml
=> ✨ Upgrade dashboard-ui dependencies

dashboard-ui/package.json, dashboard-ui/pnpm-lock.yaml
Fixes #569
Upgrade kubetail-ui dependency to 0.3.2 in order to fix invisible checkmark issue.
=> 🎣 Upgrade kubetail-ui dependency to fix checkmark issue

.github/workflows/ci.yml
Add workflow_dispatch to CI workflow.
* Modifies `.github/workflows/ci.yaml` and adds `workflow_dispatch`
=> ✨ Add workflow_dispatch to CI workflow

crates/cluster_agent/src/config.rs, crates/cluster_agent/src/main.rs
Fixes #499
Allow config cli arguments
- A new argument was added, -p or --param, which allows overriding file configurations
- Add the extra arguments to cluster agent entrypoint in the Tiltfile, e.g.
```tilt
docker_build_with_restart(
'kubetail-cluster-agent',
dockerfile='hack/tilt/Dockerfile.kubetail-cluster-agent-local',
context='.',
-    entrypoint="/cluster-agent/cluster-agent -c /etc/kubetail/config.yaml",
+    entrypoint="/cluster-agent/cluster-agent -c /etc/kubetail/config.yaml -p  logging.level=debug -p logging.format=json",     
```
- Observe that the configuration gets updated
=> 🐋Allow configuration through CLI arguments

.github/workflows/ci.yml, build/package/Dockerfile.cluster-agent, hack/tilt/Dockerfile.kubetail-cluster-agent
Fixes #493 #526
Update docker files for the new cluster agent
- Update files to follow the same approach as previously, use alpine for local development and scratch for the production 
- Add libm as it is now required
Signed-off-by: Giannis K <ikaragi23@yahoo.gr>
=> ✨Use scratch for final image

dashboard-ui/package.json, dashboard-ui/pnpm-lock.yaml, dashboard-ui/src/index.css, dashboard-ui/src/pages/home/index.tsx
=> 🎣 Update homepage styles to match Figma design

dashboard-ui/src/index.css
=>  🎣 Fix flash css

README.md
This adds adsf installation instructions to README
* Modifies README
=> 📜 Add asdf to readme

README.md
This improves the package manager install section in README.md.
* Modified README.md
=> 📜 Improve package manager section in readme

.github/workflows/publish-krew.yml
This adds missing checkout step to publish-krew workflow.
* Modified `.github/workflows/publish-krew.yaml`
=> 🎣 Add checkout step to publish-krew workflow
