backend/go.sum, backend/graph/handler.go, backend/internal/ginapp/ginapp.go, backend/internal/ginapp/graphql.go, backend/internal/ginapp/graphql_test.go, frontend/package.json, frontend/pnpm-lock.yaml, frontend/public/graphiql.html, frontend/src/apollo-client.ts, frontend/src/lib/helpers.tsx, frontend/src/pages/_root.tsx
To protect against CSWSH attacks we need a way to identify cross-site requests and prevent them from connecting to the server. The easiest way to do this is by ensuring that the request Host and Origin are the same but unfortunately, `kubectl proxy` modifies the request Host so we can't use this method. Another easy method is to check the `Sec-Fetch-Site` header but unfortunately it isn't implemented in some popular browsers (see https://github.com/kubetail-org/kubetail/issues/3) so we can't use this method either. Instead, this PR uses the old-school method of CSRF token validation to identify cross-site requests and block them. After a WebSocket connection is made, the client is required to authenticate using the CSRF token value. If the token fails validation the connection is closed, …
=> Adds protection against cross-site WebSocket hijacking using CSRF tokens

README.md
This will correct the link to the chart `values.yaml` configuration file in the `README.md`.
=> fix: readme values.yaml link

backend/README.md, backend/cmd/server/config.go, backend/cmd/server/main.go, backend/hack/server.yaml, backend/internal/ginapp/config.go, backend/internal/ginapp/ginapp.go, backend/internal/ginapp/middleware.go, backend/internal/ginapp/testutils_test.go
* Groups access-log options together under logging config
* Adds `logging.access-log.hide-health-checks` option that (default: false)
* Updated README
=> Adds a hide-health-checks option

frontend/src/lib/console/logfeed.tsx, frontend/src/pages/console.tsx
* Implements separate before/after buffers to better handle data retrieved that comes before/after logfeed content
* Adds `skipForward` internal method that allows treating unpause as a retrieval of more data
* Fixes bugs preventing follow on head/seek that returned all data
* Improves updates of start/end cursors on server fetches
=> Adds pause/unpause functionality

Dockerfile
`MKDIR` creates the directory if it doesn't exist, so we can remove these extra `RUN` layers.
https://docs.docker.com/reference/dockerfile/#workdir
=> remove unnecessary RUN commands

frontend/package.json, frontend/pnpm-lock.yaml
* @apollo/client ^3.9.10 -> ^3.9.11
* fancy-ansi ^0.1.0 -> ^0.1.1
* usehooks-ts ^3.0.2 -> ^3.1.0
* @testing-library/react ^14.2.2 -> ^14.3.1
* @types/node ^20.12.3 -> ^20.12.7
* @types/react ^18.2.74 -> ^18.2.77
* @types/react-dom ^18.2.23 -> ^18.2.25
* typescript ^5.4.3 -> ^5.4.5
* vitest ^1.4.0 -> ^1.5.0
=> Upgraded javascript dependencies

backend/cli/cmd/serve.go
* Removes server startup/shutdown from `--test` flag on CLI `serve` subcommand
=> Simplifies cli `serve --test` subcommand

hack/tilt/kubetail.yaml
Changes to hack/tilt/kubetail.yaml
* Makes cookie names more specific
* Makes Dashboard's endpointslices permissions namespace-scoped
* Removes unnecessary ClusterRole permissions for Cluster Agent
=> Improvements to tilt yaml

modules/dashboard/graph/schema.resolvers.go, modules/dashboard/graph/schema.resolvers_test.go, modules/shared/graphql/errors/errors.go
This PR blocks the following Dashboard requests in a non-desktop environment:
- KubeConfigGet
- KubeConfigWatch
- KubetailClusterAPIInstall
=> Block desktop-only requests in non-desktop environment

Tiltfile, modules/cluster-api/internal/app/app.go, modules/dashboard/internal/k8shelpers/service-account-token.go
* Remove custom audience claim from CLI token request in Dashboard
* Move GraphQL playground url to "/graphiql" in Cluster API
=> Remove custom audience from Dashboard token request and Cluster API playground url change

build/package/Dockerfile.dashboard, modules/dashboard/pkg/app/website.go, modules/shared/middleware/middleware.go
* Add "Cache-Control: public, max-age=31536000, immutable" to dashboard static assets
=> Add cache-control headers to dashboard static assets

dashboard-ui/src/components/widgets/SourcePickerModal.tsx, dashboard-ui/src/lib/hooks.ts
Prevously, the graphql queries in the console page source picker were missing kubeContext which was throwing an error. This PR fixes this issue and also fixes a typescript issue with the useCounterQueryWithSubscription custom hook that was also throwing an error.
Fix https://github.com/kubetail-org/kubetail/issues/175
=> Console source picker bug fix

modules/shared/k8shelpers/connection-manager.go
Hello ! 
Just a simple fix that permit to handle OIDC connection with the kubernetes client !
Without this fix any oidc cluster will be failed with error : `Error: no Auth Provider found for name "oidc"` 
Its a very simple fix and hope you will approve it 
thanks you
=> feat: add oidc plugin for k8s client

hack/tilt/loggen-ansi.yaml, modules/cli/cmd/logs.go, modules/cli/cmd/root.go, modules/cli/cmd/serve.go, modules/dashboard/pkg/app/app.go, modules/shared/config/config.go, modules/shared/k8shelpers/connection-manager.go, modules/shared/k8shelpers/kube-config-watcher.go
Fixes #184 
Include `--kubeconfig` as a global flag to kubetail CLI.
⚠️ `--kubeconfig` only works on `logs` and `serve` sub-command at the moment, but is visible globally.
```
add `--kubeconfig` global flag to kubetail CLI for `logs` and `serve` subcommands
```
=> new: add `--kubeconfig` to CLI

modules/cli/cmd/logs.go, modules/cli/cmd/root.go, modules/cli/cmd/serve.go, modules/dashboard/pkg/app/app.go, modules/shared/config/config.go, modules/shared/k8shelpers/connection-manager.go, modules/shared/k8shelpers/kube-config-watcher.go
=> Change scope of `--kubeconfig` CLI flag from global to local for `logs` and `serve` sub-commands

modules/shared/k8shelpers/connection-manager.go
* Set default QPS => 10.0
* Set default Burst => 40
=> Increase rate limits for kubernetes client-go

modules/cli/cmd/logs.go, modules/cli/cmd/root.go, modules/cli/cmd/serve.go, modules/cli/internal/tunnel/tunnel.go, modules/dashboard/pkg/app/app.go, modules/shared/config/config.go, modules/shared/k8shelpers/kube-config-watcher.go
Fixes #240 
`Tunnel` and `KubeconfigWatcher` now acts on `--kubeconfig` flag value. Moreover, the usage of `~` is supported.
=> Bug/240: --kubeconfig is correctly supported on serve

README.md
I've noticed that the link https://docs.tilt.dev/choosing_clusters#microk8s is broken!
Here is the correct link: https://docs.tilt.dev/choosing_clusters.html#microk8s but we can also link to the general page:  https://docs.tilt.dev/choosing_clusters.html
=> Fix broken link in README (Tilt docs cluster setup)

modules/cli/cmd/serve.go, modules/cli/go.mod, modules/cli/go.sum, modules/dashboard/internal/cluster-api/health-monitor.go
This PR fixes two issues:
1) It supresses kubernetes client-go background errors in the CLI (e.g. informer cache errors)
2) It prevents a condition where health check workers for different kube contexts were competing for the same mutex lock causing unhealthy clusters to hold up health checks for other clusters
Note: This is was done quickly so we should revisit both changes later. In particular, we need to figure out a way to expose kubernetes client-go background errors without overwhelming stdout.
Fixes https://github.com/kubetail-org/kubetail/issues/245
=> fix: supress kubernetes client-go background errors in cli and fix mutex race condition in health checker

.github/workflows/ci.yml, crates/rgkl/src/main.rs, crates/rgkl/src/stream_forward.rs, crates/rgkl/src/util/format.rs, crates/rgkl/src/util/offset.rs, crates/rgkl/src/util/writer.rs
Mostly stylistic changes to adhere to Rust coding standards outlined by `cargo fmt` and `cargo clippy`. I thought most of the clippy suggestions were good, except for its complaint on using all caps on CRI (I think that is a pedantic warning and not really applicable here where CRI is a standard abbreviation), so I've explicitly suppressed that warning.
The only functional change is un-commenting `term_tx.send()` in `main.rs`, as the early-termination logic of `TermReader` relies on this. @amorey please do to let me know if there was a specific reason why that part was commented out.
Thanks!
=> [Low Hanging Fruit] rgkl - Run Rust formatter and linter (clippy), incorporate changes

crates/rgkl/src/main.rs
Quick bugfix to the search feature.
The following piece of code: is non-blocking:
```rust
if signals.forever().next().is_some() {
drop(term_tx);
}
```
`signals.forever().next().is_some()` instead of blocking the thread (as I had initially thought) instead promptly returns a boolean, causing the program to fall through and break the search functionality.
The correct approach is to use `wait()` here as it [blocks the thread until a signal is received](https://docs.rs/signal-hook/latest/signal_hook/iterator/struct.SignalsInfo.html#method.wait), after which `term_tx` is dropped.
=> [bugfix] rgkl - resolve bug where signal await thread joins too early, breaking search

.gitignore, dashboard-ui/src/pages/console.tsx, dashboard-ui/src/pages/home.tsx, hack/tilt/multi-container.yaml
* Change behavior in logging console to show logs from all pod containers by default
* Fix UI bug where pod with multiple containers was being listed multiple times in sidebar
Fixes https://github.com/kubetail-org/kubetail/issues/271
=> Expose multiple pod containers in logging console

hack/tilt/statefulset-example.yaml, modules/shared/logs/helpers.go, modules/shared/logs/helpers_test.go
* Fix issue parsing "statefulsets" in source strings due to use of .Trim() instead of .TrimRight() to remove trailing "s"
* Add unit tests for parseWorkload() helper function
Fixes https://github.com/kubetail-org/kubetail/issues/273
=> Fix issue parsing "statefulsets" in source strings

README.md, Tiltfile, build/package/Dockerfile.cluster-agent, crates/rgkl/.cargo/config.toml, hack/tilt/Dockerfile.kubetail-cluster-agent, hack/tilt/Dockerfile.kubetail-cluster-agent-local, modules/cluster-agent/internal/services/logrecords/logrecords.go
1. Define rgkl build step as a local resource in the Tiltfile
2. Build in debug mode instead of release mode
- ~60s on first build
- ~5s on subsequent builds (pulls cached binary)
- ~60s on full re-compile
- ~5s for source files that were cached (ie reverting a change to a previous state of the source file)
- `build-rgkl`
- ~30s on first build
- <1s on subsequent builds (pulls cached binary)
- `cluster-agent` (runs after `build-rgkl` )
- ~4s always (Go build)
- `build-rgkl`
- ~30s on full initial build
- ~3s on code updates
- `cluster-agent` (runs after `build-rgkl` )
- ~4s regardless
This does bring in a few more dependencies into setting up the dev environment. Namely, the user now needs to install a **protobuf compiler** and **cross-compilation tools targeting amd64** to their local …
=> rgkl - reduce dev env Rust compile-time by moving build step to local

modules/cli/cmd/cluster_install.go, modules/cli/cmd/cluster_list.go, modules/cli/cmd/cluster_repo_add.go, modules/cli/cmd/cluster_repo_remove.go, modules/cli/cmd/cluster_repo_update.go, modules/cli/cmd/cluster_uninstall.go, modules/cli/cmd/cluster_upgrade.go, modules/cli/cmd/logs.go, modules/cli/cmd/root.go, modules/cli/cmd/serve.go, modules/dashboard/graph/schema.resolvers.go, modules/shared/helm/helm.go
Pre-work: add `kubeconfig` flag as persistent/global to all kubetail CLI commands.
shared helm.go is using `helm` cli which makes use of `*cli.EnvSettings`. This settings is used to define `kubeContext` from `--kube-context` flag. Is that the way `helm` makes use of the context? If so, I believe this _must be_ the same logic to give helm a kubeconfig.
Could you please double check @amorey
=> new: implement kubeconfig flag as global to CLI

README.md, Tiltfile, build/package/Dockerfile.cluster-agent, crates/rgkl/.cargo/config.toml, crates/rgkl/Cargo.toml, hack/tilt/Dockerfile.kubetail-cluster-agent, hack/tilt/Dockerfile.kubetail-cluster-agent-local, modules/cluster-agent/internal/services/logrecords/logrecords.go
Added an optional flag to tilt up that allows use of local builds for rgkl as opposed to containerized builds, increasing initial compile time by about 2x (60s -> 30s) and subsequent compile-times by 30x (60s -> ~2s). This will hopefully provide a solid base for growth in and contribution to the Rust sub-component(s) of the project.
- Modify dev and production cluster-agent docker images to copy executable binary and shared libraries so `rgkl` can be called without explicit call to linker 
- ⁠Use static compilation (musl) in local builds. This allows us to standardize on the executable itself. 
- ⁠⁠Call executable directly instead of using a loader in containerized builds (dev and prod). This change was required as loaders do not use musl and we have a single entrypoint …
=> 🐋 Add option to dev environment to compile Rust code incrementally on host machine

dashboard-ui/src/lib/hooks.ts, dashboard-ui/src/lib/logfeed.tsx, dashboard-ui/src/lib/util.ts
Fixes #268
This PR fixes an issue with the pin-to-bottom tailing behavior in the logging console that was causing the logs to lose their "pin". The root cause was a race condition where sometimes the scroll update was being requested before the UI had updated and a secondary issue related to how "pin-to-bottom" was being turned off.
* Added a generic `useNextTick()` hook that allows you to execute a callback after a React finishes the next commit and the browser has painted
* Used `useNextTick()` to ensure that programmatic scrolling events are triggered after log records have been added to DOM
* Modified behavior of "pin-to-bottom" logic so that behavior is turned off based on direction (scroll-up) instead of position
=> 🎣 Improve pin-to-bottom behavior when tailing in logging console

modules/cluster-agent/internal/services/logrecords/helpers.go, modules/cluster-agent/internal/services/logrecords/helpers_test.go, modules/cluster-agent/internal/services/logrecords/logrecords.go, modules/shared/clusteragentpb/cluster_agent.pb.go, modules/shared/logs/log-fetcher.go, proto/cluster_agent.proto
Fixes #298
This PR passes through container ids to the Cluster Agent at log-fetch time so that the Cluster Agent can use them to identify individual container log files on disk. Previously, the Cluster Agent was using a glob pattern with namespace, pod name and container name which was causing problems with multi-container pods where the containers shared the same prefix.
One issue that came up is that container ids returned by the Kubernetes API are prefixed with a `"<runtime>://"` string which isn't present in the file names on disk so we had to strip them first. We should keep an eye out for any situations where the runtime prefix has a different format than `"<runtime>://"`.
- Add `container_id` to logrecords service streaming request protobuf definition
- Modify log-fetcher in …
=> 🎣 Pass through container ids to Cluster Agent to fix file identification issue

dashboard-ui/src/lib/hooks.ts, dashboard-ui/src/lib/server-status.ts
Fixes #311 
This PR fixes issues in the Dashboard UI related to improper handling of the `clusterAPIEnalbed` runtime config option.
- Removes unnecessary ClusterAPI health checks that were throwing errors
- Fixes error in useIsClusterAPIEnabled() hook that wasn't returning a value when `clusterAPIEnabled` is set to false in dashboard runtime config
=> 🎣 Fix problems when cluster-api-enabled is `false` in Dashboard UI

modules/shared/go.mod, modules/shared/k8shelpers/kube-config-watcher.go, modules/shared/k8shelpers/kube-config-watcher_test.go
This PR adds an initial set of tests for the KubeConfigWatcher. Having some base set of tests should make it easier to modify the code to handle multiple files later. The test for the "Added" event is commented out because currently, KubeConfigWatcher throws an error when it is initialized with a file that doesn't exist.
- Adds unit tests to `KubeConfigWatcher`
- Ran `mod tidy` in `modules/shared` to upgrade `github.com/google/uuid` to direct import
=> 🎣 Add initial set of tests for kube-config-watcher

dashboard-ui/src/lib/server-status.ts
Update dashboard frontend to handle Cluster API "not available" health check response
- Modify server-status.ts to handle "not available" response that is emitted by `noopHealthMonitorWorker` in backend
=> 🎣 Handle Cluster API 'not available' in dashbard frontend

dashboard-ui/package.json, modules/cli/cmd/cluster_install.go, modules/cli/cmd/cluster_list.go, modules/cli/cmd/cluster_uninstall.go, modules/cli/cmd/cluster_upgrade.go, modules/cli/cmd/logs.go, modules/cli/cmd/root.go, modules/cli/cmd/serve.go, modules/cli/internal/tunnel/tunnel.go, modules/dashboard/graph/schema.resolvers.go, modules/dashboard/pkg/app/app.go, modules/shared/config/config.go, modules/shared/config/config_test.go, modules/shared/helm/helm.go, modules/shared/k8shelpers/connection-manager.go, modules/shared/k8shelpers/kube-config-watcher.go, modules/shared/k8shelpers/kube-config-watcher_test.go
Fixes #225
This PR reverts to @bavarianbidi original strategy to add support for KUBECONFIG env var by utilitzing the Kubernetes clientcmd library at config generation time, and in the process solves an uninitialized kube config bug in the previous commit. As where in the previous commit, we were doing `--kubeconfig` flag and `KUBECONFIG` env handling in the command loop, this PR offloads the loading logic to the Kubernetes clientcmd library at the time the kube config object is needed.
- Removes use of default value for `--kubeconfig` value (now default is "")
- Switches to use of `kubeconfigPath` and `WithKubeconfigPath()` where appropriate to avoid confusion with kube config object instances
- Command loops pass through value of `--kubeconfig` to lower level code that initializes kube …
=> 🎣 Fix uninitialized config bug and refactor kubeconfig handling code

modules/dashboard/graph/schema.resolvers.go, modules/shared/k8shelpers/connection-manager.go, modules/shared/k8shelpers/kube-config-watcher.go, modules/shared/k8shelpers/kube-config-watcher_test.go
Fixes #344
This PR adds support for multiple config files to KubeConfigWatcher and wraps the file system event handler with a debounce wrapper to avoid triggering multiple callbacks as part of a single config file modification write.
- Modifies KubeConfigWatcher to provide support for multiple config files via the KUBECONFIG env var
- Adds a debounce method to KubeConfigWatcher fsnotify handler to deal with potential of multiple file events as part of a single write
- Adds unit test to KubeConfigWatcher to verify support for multiple config files
- Adds unit test to KubeConfigWatcher to verify support for file changes
=> 🐋 Add support for multiple config files to KubeConfigWatcher

hack/tilt/kubetail.yaml
This PR separates the shared `ConfigMap` used in dev environment into three separate `ConfigMap`'s, one for each component (dashboard, cluster-api, cluster-agent).
- Modified `hack/tilt/kubetail.yaml`, added new `ConfigMap`'s, one each for dashboard, cluster-api, cluster-agent
- Removed shared `ConfigMap`
=> 🎣 Separate configmaps in dev environment

modules/dashboard/internal/cluster-api/health-monitor.go
Previously, we added the worker to the cache before starting it. If start failed, then non-working worker would still remain in cache, which could lead to returning a broken instance later. I don't think it is right behavior.
Now, we only store the worker in the cache after it has successfully started
- Moved caching to occur only after successful start
=> 🎣 Add worker to cache only after successful start in DesktopHealthMonitor

.github/workflows/ci.yml, crates/rust-toolchain.toml
This PR removes the use of `action-rs/toolchain` action which is has been archived and sets the Rust toolchain version to 1.87.0 using a `rust-toolchain.toml` file.
- Replace use of `action-rs/toolchain` with explict command to install Rust toolchain components using `rustup`
- Add `rust-toolchain.toml` file to `crates`/ directory
=> 🎣 Set Rust version in CI workflow to 1.87.0

crates/rust-toolchain.toml
Remove rust-toolchain.toml to give more flexibility to developers which Rust toolchain they want to use locally.
* Remove crates/rust-toolchain.toml
=> 🎣 Remove rust-toolchain.toml

modules/cluster-api/graph/server.go, modules/dashboard/graph/server.go
Fixes #404 
This PR adds an additional layer of security to our WebSocket connections by validating the Sec-Fetch-Site header, as we discussed. This change hardens our defense against Cross-Site WebSocket Hijacking (CSWSH) while maintaining compatibility for clients that don't send the header.
- The CheckOrigin function in both the Dashboard and Cluster API servers has been updated.
- It now checks if the Sec-Fetch-Site header is same-origin or same-site.
- If the header is not present, it gracefully falls back to the existing cookie-based CSRF validation in the InitFunc.
- This change is purely additive and does not remove any of the existing CSRF protections, making it a safe first step.
- ✅ Add the correct emoji to the PR title
- ✅  Link the issue number, if any, to *Fixes #*
- ✅  Add …
=> 🎣 feat: Add Sec-Fetch-Site validation for WebSocket connections

Makefile, crates/rgkl/README.md, dashboard-ui/README.md, modules/README.md, modules/dashboard/README.md
- 🐋 New feature
Fixes https://github.com/kubetail-org/kubetail/issues/401
Add targets for linting, vetting, and testing for all components (Rust crates, Go modules, and dashboard UI) based on the CI workflow to Makefile.
* Added new Rust-related targets (`crates-build`, `crates-lint`, `crates-vet`, `crates-test`) and Go-related targets (`modules-lint`, `modules-test`, `modules-vet`) to the `Makefile`, enabling streamlined builds, linting, testing, and vetting for both ecosystems. Also introduced combined targets like `lint-all`, `test-all`, and `ci-checks` for comprehensive CI checks.
* Introduced Rust toolchain detection (`RUST_VERSION` and `RUST_ARCH`) and added directory variables (`CRATES_DIR` and `MODULES_DIR`) for better modularity in the `Makefile`.
=> 🐋 feat: add Rust crates, Dashboard and Go modules lint/vet CI targets to Makefile

.github/renovate.json
Fixes #418 
- Removes mergeConfidence feature since it needs credentials and maybe is not free to use 
- Just removes the mergeConfidence from the renovate.json
=> 🎣 fix(renovate): remove mergeConfidence

modules/dashboard/internal/cluster-api/health-monitor_test.go
Fixes #396
This PR introduce unit tests for `HealthMonitor`
Added tests in `health-monitor_test.go`. Tests covered the following functions 
* `NewHealthMonitor`
* `Shutdown`
* `GetHealthStatus`
* `WatchHealthStatus`
* `ReadyWait`
=> 🐋 Add unit tests health monitor

modules/cli/go.mod, modules/cli/go.sum, modules/cluster-agent/go.mod, modules/cluster-agent/go.sum, modules/cluster-agent/internal/services/logmetadata/helpers.go, modules/cluster-agent/internal/services/logmetadata/helpers_test.go, modules/cluster-api/go.mod, modules/cluster-api/go.sum, modules/dashboard/go.mod, modules/dashboard/go.sum, modules/go.work.sum, modules/shared/go.mod, modules/shared/go.sum
This PR fixes fsnotify to to v1.8.0 to fix a regression bug causing test failures on macos. It also makes a small improvement to how we're checking fsnotify events.
- Fix fsnotify to v1.8.0 in each go module
- Use fsnotify event `.Has()` method to check for events in cluster agent logmetadata helper.
=> 🎣 Fixed regression bug from previous fsnotify upgrade

dashboard-ui/package.json, dashboard-ui/pnpm-lock.yaml
This PR upgrades dashboard-ui to vite 6 and removes unnecessary dependencies.
- Vite => 6.3.5
- Vitest => 3.2.4
-  @vitejs/plugin-react-swc => 3.10.2
- Removed @babel/core
- Removed globals
=> ✨ Upgrade to vite 6, removed unnecessary dependencies

Tiltfile, hack/config.yaml, hack/tilt/kubetail.yaml, modules/cluster-api/README.md, modules/cluster-api/cmd/main.go, modules/dashboard/README.md, modules/shared/config/config.go
Fixes #389 
Add http and https support for cluster-api-server.
- adding the ability to use http and/or https port for cluster api server
- both ports are enabled by default
- update README.md of dashboard and cluster-api go module
=> 🐋 Add dual port support to cluster-api server (HTTP + HTTPS)

CLAUDE.md, dashboard-ui/package.json, dashboard-ui/pnpm-lock.yaml, dashboard-ui/src/components/widgets/ServerStatus.tsx, dashboard-ui/src/lib/logfeed.tsx, dashboard-ui/src/pages/home.tsx
Fixes #505
This pull request migrates the application's state management from the archived Recoil library to Jotai. This is a necessary refactor to enable a future upgrade to React 19, as Recoil is no longer maintained.
- Replaced the `recoil` dependency with `jotai` for React 19 compatibility.
- Migrated state management logic in key components like `logfeed`, `ServerStatus`, and the `home` page.
- Updated the `CLAUDE.md` documentation to reflect the new state management library.
=> ✨ Migrate from Recoil to Jotai  

.github/workflows/release-cli.yml
Fixes #455 
This PR fixes shasum ordering issue where checksums were being calculated before signing binaries. It also refactors release-cli workflow and consolidates checksums into one step before creating GitHub release.
- Calculate SHA-256 checksum after signing windows binaries
- Calculate SHA-256 checksums in one step before creating GH release
=> 🎣 Fix shasum calculation order issue in release-cli workflo and refactor

crates/Cargo.lock, crates/cluster_agent/Cargo.toml, crates/cluster_agent/src/logmetadata.rs, crates/cluster_agent/src/logrecords.rs, crates/cluster_agent/src/main.rs
Implements List of LogMetadata service
- Adds the implementation for List of the metadata service
- I added kube and k8s-openapi dependencies when I was trying things but didn't remove them since we are going to need them eventually.
- Ensure that the tests are passing (`cargo test`)
As the integration with the UI does not work yet, follow the steps below to test the gRPC services (although there might be a better way to do it):
- Install [grpcurl](https://github.com/fullstorydev/grpcurl)
- Start the dev environment `tilt up`
- Get the loggen pod name, container id, and the cluster agent pod name with:
```
kubectl get pods --all-namespaces \
--field-selector spec.nodeName=minikube-m03 \
-o json | jq -r '
.items[] | 
. as $pod |
$pod.status.containerStatuses[]? | …
```
=> Implement List of LogMetadata 🐋

modules/shared/k8shelpers/connection-manager.go, modules/shared/k8shelpers/connection-manager_test.go, modules/shared/util/syncmap.go, modules/shared/util/syncmap_test.go
The goal of this PR is to fix intermittent slow startup times in the Kubetail Dashboard when running in a desktop environment. The cause is lock contention in `DesktopConnectionManager` across clusters due to the the singleton `sync.Mutex` used by instances of the struct. To fix this issue, this PR adds threadsafe `LoadOrCompute()` and `LoadOrComputeWithContext()` methods to the `SyncMap` implementation and uses them to replace the global `sync.Mutex` in `DesktopConnectionManager`.
Note: `LoadOrCompute()` is essentially a thread-safe memoization method so it seems like there should already be something in the standard library or a third-party implementation we can use instead. When I looked around I found the [singleflight](https://pkg.go.dev/golang.org/x/sync/singleflight) library but it …
=> 🎣 Switch to using `SyncMap` in desktop connection manager to fix slow startup times

hack/config.yaml, hack/tilt/kubetail.yaml, modules/cli/cmd/serve.go, modules/cluster-api/README.md, modules/cluster-api/cmd/main.go, modules/dashboard/README.md, modules/dashboard/cmd/main.go, modules/dashboard/hack/config.yaml, modules/shared/config/config.go
This PR reverts to single-port http endpoints in the Kubetail Dashboard and the Kubetail Cluster Agent servers. In a recent commit we added support for dual-port http/https endpoints but upon further reflection it's better to keep the original behavior (single-port has less operational complexity, less security risk and is inline with Kubernetes' own API server behavior). Since we haven't issued a release since the dual-port commit, this PR represents a non-breaking change from the point of view of users. We may want to make breaking changes in the future but the only goal of this PR was to revert to the previous behavior.
* Modify `hack/config.yaml` and revert to old single-port config schema
* Modify `modules/shared/config/config.go` and implement old single-port schema
* Modify …
=> ✨ Revert to single-port http endpoints in Dashboard and Cluster Agent

dashboard-ui/package.json, dashboard-ui/pnpm-lock.yaml
On July 18, 2025 the maintainer of `eslint-config-prettier` notified the public that he was the victim of a phishing attack and that the attacker had published several malicious packages using his credentials ([CVE-2025-54313](https://nvd.nist.gov/vuln/detail/CVE-2025-54313)). Luckily we hadn't upgraded to those packages so we weren't affected directly but we still want to bump the dependencies to the newly published safe versions.
* eslint-config-prettier => 10.1.8
* eslint-plugin-prettier => 5.5.3
* synckit => 0.11.11
* napi-postinstall => 0.3.2
=> 🎣 Security fix: handle `eslint-config-prettier` compromise (CVE-2025-54313)

modules/cli/cmd/serve.go
Previously, the Kubetail CLI `serve` sub-command would issue a fatal exit if it was unable to open a new browser tab. This PR modifies the behavior and issues a warning instead of exiting the command loop.
* Replaced `zlog.Fatal()` with `zlog.Warn()` in `modules/cli/cmd/serve.go`
=> 🎣 Issue warning on browser open error instead of fatal exit

dashboard-ui/src/lib/logfeed.tsx
This PR fixes an issue with scroll lock timing when scrolling up in the log feed viewer that was introduced with the Jotai migration. The desired behavior is that the apparent scroll position should be maintained when the user scrolls up and new data is fetched and prepended to the cache. This behavior was working properly with Recoil but broke with Jotai because apparently the libraries have different DOM update timings. This PR fixes the issue by wrapping the scroll lock logic in a `nextTick()` instead of a `setTimeout()`.
- Replaced use of `setTimeout()` for timing with `nextTick()`
=> 🎣 Fix scroll timing issue in logfeed viewer

.github/workflows/release-cli.yml
Adds upload signed artifacts step to release-cli workflow. Previously signed artifacts were being downloaded but not re-uploaded so final GitHub release contained unsigned binaries.
=> 🎣 Add upload signed artifacts step to release-cli workflow

crates/Cargo.lock, crates/cluster_agent/Cargo.toml, crates/cluster_agent/src/logmetadata.rs, crates/cluster_agent/src/logmetadata/logmetadata_watcher.rs, crates/cluster_agent/src/logrecords.rs, crates/cluster_agent/src/main.rs, proto/cluster_agent.proto
Fixes #491
Implements the watch service for LogMetadata. 
There are some limitations to this service that stem from how the filesystem works. From investigating online it seems that we should consider events coming from notify more like an event of "something has changed" as the events are generally not consistent. Some of these inconsistencies can be found in [notify's documentation](https://docs.rs/notify/latest/notify/).
Events are debounced by using notify's debouncer every 2 seconds for each file. As we are mapping many event types, to only three types, there is still some possibility of duplicate events currently.
There are some improvements that I will implement as part of a subsequent PR:
- Improve error handling
- Deduplicate events using an IndexSet.
- Ensure that the tests are …
=> 🐋 Implement Watch of LogMetadataService

crates/cluster_agent/Cargo.toml, crates/cluster_agent/src/log_metadata/log_metadata_watcher.rs
Fixes #590 
Another step was added after the transformation that removes the duplicate events.
- This also includes the changes from https://github.com/kubetail-org/kubetail/pull/589 as I based this work on that branch
- Switched the Vec<LogMetadataWatchEvent> to a VecDeque to better support building the list of events from end to start
- The reverse construction happens to ensure that the most recent event is sent from gRPC service
- Follow the testing instructions in #572 and observe that no duplicate events are created
- Observe in tests that no duplicate events are now created.
Signed-off-by: Giannis K <ikaragi23@yahoo.gr>
=> 🎣 Deduplicate Metadata events

crates/Cargo.lock, crates/cluster_agent/Cargo.toml, crates/cluster_agent/src/config.rs, crates/cluster_agent/src/main.rs
Fixes #608
Updates the configuration to be populated with env variables
- File is now loaded by our code instead of config to grab the contents as a string
- We use subst crate to replace the env variables
- Add an env variable to `kubetail.yaml`, for example:
```yaml
containers:
- name: kubetail-cluster-agent
image: kubetail-cluster-agent
ports:
- name: grpc
protocol: TCP
containerPort: 50051
env:
- name: NODE_NAME
valueFrom:
fieldRef:
fieldPath: spec.nodeName
+            - name: DEBUG_LEVEL
+              value: debug
```
- Add the variable for the cluster agent config file (both $DEBUG_LEVEL and ${DEBUG_LEVEL} should work):
```yaml
labels:
app.kubernetes.io/name: kubetail
app.kubernetes.io/component: cluster-agent
data:
config.yaml: |
cluster-agent:
addr: :50051
logging:
enabled: true …
```
=> 🐋Allow env variable substitution

crates/cluster_agent/src/log_metadata.rs, crates/cluster_agent/src/log_metadata/log_metadata_watcher.rs, crates/rgkl/Cargo.toml, crates/rgkl/src/stream_forward.rs
Fixes #635
Improves the stability and reduces the run time of Rust tests
- Specify a different namespace on each test, to allow the tests to run independently.
- Allow callers of LogMetadataWatcher::watch to specify the watcher type, to allow using stable watchers during testing
- Change all tests apart from `test_create_events_are_generated` to run in parallel. This test isn't possible to run in parallel, as `PollWatcher` throws errors when a tracked file is deleted from another test running in parallel.
- Use barriers or waiting on a precondition instead of sleeping to synchronise threads when testing.
- Use async tasks everywhere instead of creating new threads
- Observe that the tests pass.
- Run the tests and observe that the running time is reduced.
Generally, the notify `Watcher`s …
=> ✨Add barriers instead of sleeping in tests, use kqueue in macos

.github/ci-config/chocolatey/chocolateyInstall.ps1.tmpl, .github/ci-config/chocolatey/kubetail.nuspec.tmpl, .github/workflows/publish-chocolatey.yml
Fixes #315  
This PR adds a GitHub Actions workflow that pushes new Kubetail CLI releases to the Kubetail [choco-packages](https://github.com/kubetail-org/choco-packages) repo automatically. When a new CLI release is created, it fetches the shasums from the release and uses them to create new manifest files for the package. Then it creates a new PR in choco-packages repo where further processing is done.
* Add `kubetail.nuspec.tmpl` file
* Add `chocolateyInstall.ps1.tmpl` file
* Add `publish-chocolatey.yml` workflow
=> 🐋 Push new releases to choco-packages repo automatically

.github/actions/setup-environment/action.yml, build/package/Dockerfile.cluster-agent, crates/cluster_agent/src/main.rs, hack/tilt/Dockerfile.kubetail-cluster-agent
Fixes #655 
This PR upgrades to Rust 1.90.0. It also fixes a compiler warning about unnecessary parentheses in a type argument.
* Upgrades to Rust 1.90.0 in dev and production Cluster Agent docker images
* Upgrades to Rust 1.90.0 in CI workflow
* Removes unnecessary parentheses in type argument in `crates/cluster_agent/main.rs`
=> ✨ Upgrade to Rust 1.90.0

.github/workflows/release-cluster-agent.yml, .github/workflows/release-cluster-api.yml, .github/workflows/release-dashboard.yml
This PR adds opencontainer annotations to the GHCR image manifests to fix issue with missing package links on GitHub repo page.
=> 🎣 Add opencontainer annotations to GHCR image manifest

dashboard-ui/src/index.css, dashboard-ui/src/pages/home/index.tsx
This PR removes unnecessary code from the Tailwind V4 migration that re-defined the default border color as `--gray-200`. Now the default border color is `var(--border)`. It also makes a hover border color in the homepage sidebar lighter for dark mode.
=> 🎣 Fix default border color issue

.github/actions/setup-environment/action.yml
Recently, the rust-toolchain action we use in our workflows started returning an error. It's probably related to the recent release of Rust 1.90.0. This PR fixes the problem by removing the toolchain version override. The default version is 1.90.0 so it won't affect our current actions but we may need to revisit this issue in the future.
=> 🎣 Fix GHA Rust toolchain issue

Makefile
This modifies the rustc version check in our Makefile to fail silently if rustc isn't available in order to remove warnings when running `make build` in systems without rustc (Rust isn't required for a CLI build).
* Modified `Makefile`
=> 🎣 Fix warning from missing rustc when running `make build`
